// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ActionOpt {
    "WindowName": string;
    "ActionName": string;

    /** Creates a new ActionOpt instance. */
    constructor($$source: Partial<ActionOpt> = {}) {
        if (!("WindowName" in $$source)) {
            this["WindowName"] = "";
        }
        if (!("ActionName" in $$source)) {
            this["ActionName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionOpt instance from a string or object.
     */
    static createFrom($$source: any = {}): ActionOpt {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActionOpt($$parsedSource as Partial<ActionOpt>);
    }
}

export class WindowStatus {
    /**
     * 窗口名称
     */
    "WindowName": string;

    /**
     * 宽度
     */
    "Width": number;

    /**
     * 高度
     */
    "Height": number;

    /**
     * 可用宽度
     */
    "AvailWidth": number;

    /**
     * 可用高度
     */
    "AvailHeight": number;

    /**
     * 屏幕左上角位置
     */
    "ScreenLeft": number;

    /**
     * 屏幕左上角位置
     */
    "ScreenTop": number;

    /**
     * 内部宽度
     */
    "InnerWidth": number;

    /**
     * 内部高度
     */
    "InnerHeight": number;

    /**
     * 当前 DPR
     */
    "Dpr": number;

    /**
     * 是否全屏
     */
    "IsFullscreen": boolean;

    /**
     * 是否是扩展屏幕
     */
    "IsExtended": boolean;

    /**
     * 是否最大化
     */
    "IsMaximise": boolean;

    /**
     * 是否最小化
     */
    "IsMinimise": boolean;

    /**
     * 是否聚焦
     */
    "IsFocused": boolean;

    /** Creates a new WindowStatus instance. */
    constructor($$source: Partial<WindowStatus> = {}) {
        if (!("WindowName" in $$source)) {
            this["WindowName"] = "";
        }
        if (!("Width" in $$source)) {
            this["Width"] = 0;
        }
        if (!("Height" in $$source)) {
            this["Height"] = 0;
        }
        if (!("AvailWidth" in $$source)) {
            this["AvailWidth"] = 0;
        }
        if (!("AvailHeight" in $$source)) {
            this["AvailHeight"] = 0;
        }
        if (!("ScreenLeft" in $$source)) {
            this["ScreenLeft"] = 0;
        }
        if (!("ScreenTop" in $$source)) {
            this["ScreenTop"] = 0;
        }
        if (!("InnerWidth" in $$source)) {
            this["InnerWidth"] = 0;
        }
        if (!("InnerHeight" in $$source)) {
            this["InnerHeight"] = 0;
        }
        if (!("Dpr" in $$source)) {
            this["Dpr"] = 0;
        }
        if (!("IsFullscreen" in $$source)) {
            this["IsFullscreen"] = false;
        }
        if (!("IsExtended" in $$source)) {
            this["IsExtended"] = false;
        }
        if (!("IsMaximise" in $$source)) {
            this["IsMaximise"] = false;
        }
        if (!("IsMinimise" in $$source)) {
            this["IsMinimise"] = false;
        }
        if (!("IsFocused" in $$source)) {
            this["IsFocused"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowStatus($$parsedSource as Partial<WindowStatus>);
    }
}
