// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as global$0 from "./global/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./types/models.js";

/**
 * Action 通信
 */
export function Action(opt: types$0.ActionOpt): $CancellablePromise<void> {
    return $Call.ByID(561326412, opt);
}

/**
 * 加法器
 */
export function Add(n1: number, n2: number): $CancellablePromise<string> {
    return $Call.ByID(4039261333, n1, n2);
}

/**
 * 还原悬浮球
 */
export function BallWindowReset(): $CancellablePromise<void> {
    return $Call.ByID(1271690950);
}

/**
 * 放大悬浮球
 */
export function BallWindowZoomIn(): $CancellablePromise<void> {
    return $Call.ByID(3190062279);
}

/**
 * 获取所有窗口的信息
 */
export function GetAllWindowInfo(): $CancellablePromise<global$0.WebWindowType> {
    return $Call.ByID(4028914641).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetBallWindowZoomDir(): $CancellablePromise<global$0.BallWindowType> {
    return $Call.ByID(4166611755).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * 暴露给前端的用户获取当前窗口信息的方法
 */
export function GetWindowInfo(WindowName: string): $CancellablePromise<global$0.WebviewWindow> {
    return $Call.ByID(3231228814, WindowName).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * 打开悬浮球窗口
 */
export function OpenBallWindow(): $CancellablePromise<void> {
    return $Call.ByID(1907924039);
}

/**
 * 打开测试窗口
 */
export function OpenTestWindow(): $CancellablePromise<void> {
    return $Call.ByID(2213258802);
}

/**
 * 从前端传来的窗口变化的信息
 */
export function WindowChange(opt: types$0.WindowStatus): $CancellablePromise<void> {
    return $Call.ByID(2206134062, opt);
}

// Private type creation functions
const $$createType0 = global$0.WebWindowType.createFrom;
const $$createType1 = global$0.BallWindowType.createFrom;
const $$createType2 = global$0.WebviewWindow.createFrom;
