// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

export class BallWindowType {
    /**
     * 放大后的宽度
     */
    "ZoomInW": number;

    /**
     * 放大后的高度
     */
    "ZoomInH": number;

    /**
     * 原始宽度
     */
    "OrgW": number;

    /**
     * 原始高度
     */
    "OrgH": number;

    /**
     * 原始位置Y
     */
    "OrgY": number;

    /**
     * 原始位置X
     */
    "OrgX": number;

    /**
     * 屏幕宽度
     */
    "ScreenW": number;

    /**
     * 屏幕高度
     */
    "ScreenH": number;

    /**
     * 放大方向
     */
    "ZoomDir": string;

    /**
     * 是否置顶
     */
    "IsPinTop": boolean;

    /** Creates a new BallWindowType instance. */
    constructor($$source: Partial<BallWindowType> = {}) {
        if (!("ZoomInW" in $$source)) {
            this["ZoomInW"] = 0;
        }
        if (!("ZoomInH" in $$source)) {
            this["ZoomInH"] = 0;
        }
        if (!("OrgW" in $$source)) {
            this["OrgW"] = 0;
        }
        if (!("OrgH" in $$source)) {
            this["OrgH"] = 0;
        }
        if (!("OrgY" in $$source)) {
            this["OrgY"] = 0;
        }
        if (!("OrgX" in $$source)) {
            this["OrgX"] = 0;
        }
        if (!("ScreenW" in $$source)) {
            this["ScreenW"] = 0;
        }
        if (!("ScreenH" in $$source)) {
            this["ScreenH"] = 0;
        }
        if (!("ZoomDir" in $$source)) {
            this["ZoomDir"] = "";
        }
        if (!("IsPinTop" in $$source)) {
            this["IsPinTop"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BallWindowType instance from a string or object.
     */
    static createFrom($$source: any = {}): BallWindowType {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BallWindowType($$parsedSource as Partial<BallWindowType>);
    }
}

/**
 * 定义有哪些窗口
 */
export class WebWindowType {
    "Main": WebviewWindow;
    "Test": WebviewWindow;
    "Ball": WebviewWindow;

    /** Creates a new WebWindowType instance. */
    constructor($$source: Partial<WebWindowType> = {}) {
        if (!("Main" in $$source)) {
            this["Main"] = (new WebviewWindow());
        }
        if (!("Test" in $$source)) {
            this["Test"] = (new WebviewWindow());
        }
        if (!("Ball" in $$source)) {
            this["Ball"] = (new WebviewWindow());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebWindowType instance from a string or object.
     */
    static createFrom($$source: any = {}): WebWindowType {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Main" in $$parsedSource) {
            $$parsedSource["Main"] = $$createField0_0($$parsedSource["Main"]);
        }
        if ("Test" in $$parsedSource) {
            $$parsedSource["Test"] = $$createField1_0($$parsedSource["Test"]);
        }
        if ("Ball" in $$parsedSource) {
            $$parsedSource["Ball"] = $$createField2_0($$parsedSource["Ball"]);
        }
        return new WebWindowType($$parsedSource as Partial<WebWindowType>);
    }
}

/**
 * 定义窗口结构体
 */
export class WebviewWindow {
    "Window": application$0.WebviewWindow | null;

    /**
     * 窗口名称
     */
    "Name": string;

    /**
     * 是否已启用监听事件
     */
    "IsListen": boolean;

    /**
     * 启用无边框模式
     */
    "EnableFrameless": boolean;

    /**
     * 是否正在运行
     */
    "IsRunner": boolean;

    /**
     * 当前窗口的 DPR 值
     */
    "NowDpr": number;

    /**
     * 原始 DPR 值
     */
    "OrgDpr": number;

    /**
     * 窗口是否显示
     */
    "IsShow": boolean;

    /**
     * 窗口 X 坐标
     */
    "X": number;

    /**
     * 窗口 Y 坐标
     */
    "Y": number;

    /**
     * 窗口宽度
     */
    "W": number;

    /**
     * 窗口高度
     */
    "H": number;

    /** Creates a new WebviewWindow instance. */
    constructor($$source: Partial<WebviewWindow> = {}) {
        if (!("Window" in $$source)) {
            this["Window"] = null;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("IsListen" in $$source)) {
            this["IsListen"] = false;
        }
        if (!("EnableFrameless" in $$source)) {
            this["EnableFrameless"] = false;
        }
        if (!("IsRunner" in $$source)) {
            this["IsRunner"] = false;
        }
        if (!("NowDpr" in $$source)) {
            this["NowDpr"] = 0;
        }
        if (!("OrgDpr" in $$source)) {
            this["OrgDpr"] = 0;
        }
        if (!("IsShow" in $$source)) {
            this["IsShow"] = false;
        }
        if (!("X" in $$source)) {
            this["X"] = 0;
        }
        if (!("Y" in $$source)) {
            this["Y"] = 0;
        }
        if (!("W" in $$source)) {
            this["W"] = 0;
        }
        if (!("H" in $$source)) {
            this["H"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebviewWindow instance from a string or object.
     */
    static createFrom($$source: any = {}): WebviewWindow {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Window" in $$parsedSource) {
            $$parsedSource["Window"] = $$createField0_0($$parsedSource["Window"]);
        }
        return new WebviewWindow($$parsedSource as Partial<WebviewWindow>);
    }
}

// Private type creation functions
const $$createType0 = WebviewWindow.createFrom;
const $$createType1 = application$0.WebviewWindow.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
